# Generated by Django 2.1.7 on 2019-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(default='kkkk', max_length=200)),
                ('series_director', models.CharField(max_length=100)),
                ('series_synopsis', models.CharField(max_length=1000)),
                ('series_poster', models.FileField(upload_to='')),
                ('series_release_date', models.DateField(default='0000', verbose_name='Date')),
                ('series_budget', models.IntegerField()),
                ('series_box_office', models.IntegerField()),
                ('series_genre', models.CharField(default='Action', max_length=100)),
                ('series_rating', models.FloatField()),
            ],
        ),
    ]
