# Generated by Django 2.1.7 on 2019-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='series_director',
            new_name='series_creator1',
        ),
        migrations.AddField(
            model_name='series',
            name='series_creator2',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
