# Generated by Django 2.1.7 on 2019-08-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series_app', '0002_auto_20190812_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='series_box_office',
            new_name='series_gross',
        ),
    ]
