# Generated by Django 2.1.7 on 2019-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series_episodes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series_episodes',
            old_name='series_episode_box_office',
            new_name='series_episode_gross',
        ),
    ]
