# Generated by Django 2.1.7 on 2019-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series_episodes_app', '0002_auto_20190818_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_episodes',
            name='series_episode_director',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='series_episodes',
            name='series_episode_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='series_episodes',
            name='series_episode_series_title',
            field=models.CharField(default='Planet Earth', max_length=200),
        ),
        migrations.AlterField(
            model_name='series_episodes',
            name='series_episode_thumbnail',
            field=models.FileField(default='Planet Earth Thumbnail', upload_to=''),
        ),
        migrations.AlterField(
            model_name='series_episodes',
            name='series_episode_video',
            field=models.FileField(default='PlanetEarth.mp4', upload_to=''),
        ),
    ]
