# Generated by Django 2.1.7 on 2019-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentaries_Episodes',
            fields=[
                ('documentary_episode_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('documentary_episode_documentaries_title', models.CharField(default='oooppp', max_length=200)),
                ('documentary_episode_season', models.IntegerField(default=1)),
                ('documentary_episode_number', models.IntegerField(default=0)),
                ('documentary_episode_director', models.CharField(max_length=100)),
                ('documentary_episode_synopsis', models.CharField(max_length=1000)),
                ('documentary_episode_title', models.CharField(max_length=100)),
                ('documentary_episode_poster', models.FileField(upload_to='')),
                ('documentary_episode_thumbnail', models.FileField(default='dajadaja', upload_to='')),
                ('documentary_episode_release_date', models.DateField(default='0000', verbose_name='Date')),
                ('documentary_episode_budget', models.IntegerField()),
                ('documentary_episode_box_office', models.IntegerField()),
                ('documentary_episode_genre', models.CharField(default='Action', max_length=100)),
                ('documentary_episode_format', models.CharField(max_length=100)),
                ('documentary_episode_rating', models.FloatField()),
                ('documentary_episode_video', models.FileField(default='jadajada', upload_to='')),
            ],
        ),
    ]
