# Generated by Django 2.1.7 on 2019-08-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries_episodes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaries_episodes',
            name='documentary_episode_director',
            field=models.CharField(max_length=1000),
        ),
    ]
