# Generated by Django 2.1.7 on 2019-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries_episodes_app', '0002_auto_20190818_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentaries_episodes',
            old_name='documentary_episode_box_office',
            new_name='documentary_episode_gross',
        ),
    ]
