# Generated by Django 2.1.7 on 2019-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentaries_episodes_app', '0003_auto_20190818_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaries_episodes',
            name='documentary_episode_documentaries_title',
            field=models.CharField(default='Planet Earth', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentaries_episodes',
            name='documentary_episode_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentaries_episodes',
            name='documentary_episode_thumbnail',
            field=models.FileField(default='Planet Earth poster', upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentaries_episodes',
            name='documentary_episode_video',
            field=models.FileField(default='PlanetEarth.mp4', upload_to=''),
        ),
    ]
