# Generated by Django 2.1.7 on 2019-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_synopsis', models.CharField(max_length=1000)),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_poster', models.FileField(upload_to='')),
                ('movie_thumbnail', models.FileField(default='dajadaja', upload_to='')),
                ('movie_release_date', models.DateField(default='1899', verbose_name='Date')),
                ('movie_budget', models.IntegerField()),
                ('movie_box_office', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_format', models.CharField(max_length=100)),
                ('movie_rating', models.FloatField()),
                ('movie_video', models.FileField(upload_to='')),
            ],
        ),
    ]
