# Generated by Django 2.1.7 on 2019-08-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_auto_20190818_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
