# Generated by Django 2.1.7 on 2019-08-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_auto_20190818_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_id',
            new_name='movie_id_field',
        ),
    ]
