# Generated by Django 2.1.7 on 2019-08-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0007_auto_20190818_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_box_office',
            new_name='movie_gross',
        ),
    ]
